name: Zephyr Coverage

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 2 * * *'

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          west init -l .
          west update
          west build -b native_sim -d build/coverage \
            -- -DCONFIG_OVERLAY_CONFIG=boards/native_sim/coverage.conf
          ./build/coverage/zephyr/zephyr.exe
          gcovr -r . \
            --exclude 'zephyr/.*' \
            --exclude 'build/.*' \
            --xml -o coverage.xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

